### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by antiprime** [mruby-zest/mruby-nanovg#1]
A license file and README notice should be added to this repository to clarify which license it is released under.

**Comment by fundamental** [comment]
As per https://github.com/mruby-zest/mruby-nanovg/blob/master/mrbgem.rake this repo is licensed under the MIT license. When adding the LICENSE/README those clarifications should be sent upstream to https://github.com/IceDragon200/mruby-nanovg as well.

**Comment by antiprime** [comment]
Ah, I didn't realize the license was stated in that file.
